__author__ = 'leena'


def get_template_name(category):
    return {"space_progress": "space_progress",
            "space_completion_reminder": "space_completion_reminder",
            "space_status_change": "space_status_change",
            "space_status_publish": "space_status_publish",
            "space_status_complete": "space_status_complete",
            "space_cityadd": "space_cityadd",
            "space_new" : 'space_new',
            "space_await_approval" : "space_await_approval",
            "enq_space": "enq_space",
            "enq_reply":"enq_reply",
            "enq_reply_provider":"enq_reply_provider",
            "enq_reply_seeker":"enq_reply_seeker",
            "enq_status": "enq_status",
            "enq_closed":"enq_closed",
            "enq_accept":"enq_accept",
            "enq_reject":"enq_reject",
            "enq_created": "enq_created",
            "enq_noreply": "enq_noreply",
            "book_new": "book_new",
            "book_accept": "book_accept",
            "book_reject": "book_reject",
            "book_reminder": "book_reminder",
            "book_cancel": "book_cancel",
            "book_cancel_seeker": "book_cancel_seeker",
            "book_cancel_approve": "book_cancel_approve",
            "book_cancel_disapp": "book_cancel_disapp",
            "book_cancel_request" :"book_cancel_req",
            "book_incomplete_rem": "book_incomp_rem",
            "book_receipt": "book_receipt",
            "book_invite": "book_invite",
            "book_meet_cancel": "book_meet_cancel",
            "book_noreply": "book_noreply",
            "req_created": "req_created",
            "req_reminder": "req_reminder",
            "req_suggestion": "req_suggestion",
            "req_new": "req_new",
            "req_reply": "req_reply",
            "req_noreply": "req_noreply",
            "revoke_space": "revoke_space",
            "space_awaited_approval": "space_await_approval",
            "feedback_space": "feedback_space",
            "feedback_system": "feedback_system",
            "change_pwd": "change_pwd",
            "forgot_pwd": "forgot_pwd",
            "invite_referral": "invite_referral",
            "new_booking": "new_booking",
            "signup": "signup",
            "space_add":"space_add",
            "transact_progress" :"transact_progress",
            "proposal":"proposal"
    }[category]

